docusaurus.config.js
package-lock.json
package.json
src/css/custom.css

Add search

---

.github/actions/finalize/action.yml

Signed-off-by: Kyle Harding <kyle@balena.io>

Update custom Flowzone finalize action to use new inputs

---

.github/actions/finalize/action.yml
docusaurus.config.js
src/pages/CHANGELOG.md
src/pages/markdown-page.md

Expose change log

---

.github/actions/clean/action.yml
.github/actions/publish/action.yml

Signed-off-by: Kyle Harding <kyle@balena.io>

Update workflow step descriptions

---

docs/how-we-work/resource-glossary/milestones.md
docs/how-we-work/resource-glossary/support-tickets.md
docs/how-we-work/resource-glossary/threads.md

Signed-off-by: 20k-ultra <3946250+20k-ultra@users.noreply.github.com>

Include descriptions for milestones, support tickets, and threads.

---

docs/glossary.md

change-type: major
signed-off-by: laura alison <laura@balena.io>

Add balena glossary

---

docs/how-we-work/contracts-glossary/brainstorm-calls.md

Add more information about prod/arch calls

---

docusaurus.config.js

Correct changelog spelling fixes #18

---

docs/tooling/model-framework.md

Change-type: minor
Signed-off-by: AlidaOdendaal <alida@balena.io>

docs/tooling: Add a new section related to Model Framework

---

docs/how-we-work/contracts-glossary/brainstorm-calls.md

Update hardware call info

---

docs/policies/home-office-and-equipment-policy.md

Updated and Moved Purchasing information section to the top 
Change-type:minor
Signed-off-by: Lampros Papapostolou <lampros.papapostolou@balena.io>

Updated Purchasing Information

---

docs/balenalabs/README.md
docs/balenalabs/github-orgs.md
docs/balenalabs/how-we-work.md
docs/balenalabs/other-meetings.md
docs/balenalabs/project-board.md
docs/balenalabs/project-guide.md
docs/balenalabs/project-guidelines.md
docs/balenalabs/project-support.md
docs/balenalabs/strategy.md

Update Labs sections with new strategy content

---

docs/balenalabs/project-support.md

Remove Project Clinic from balenaLabs docs

---

docs/access-requests/README.md

Changed the tool that we use for #access from Jellyfish to Zulip.
Change-type: minor
Signed-off-by: Lpapapo<lampros.papapostolou@balena.io>

#access request from Jellyfish to Zulip.md

---

docs/balena-20-resources/README.md
docs/glossary.md

Add a section to record updates on how balena operates / the way we work
change-type: major
signed-off-by: laura alison <laura@balena.io>

Add Balena 2.0 section

---

docs/policies/parental-leave-policy.md

Parental Leave policy Review
Detailed review of Parental leave policy February 2023
Change-type: major
Signed-off-by: Alexandros Sakellariou<Alexandros.Sakellariou@balena.io>

Review parental-leave-policy.md

---

docs/policies/leave-policy.md

Unlimited leave policy replacing previous leave policy
Change-type: major
Signed-off-by: Alexandros Sakellariou<Alexandros.Sakellariou@balena.io>
unlimited leave-People-ops

Unlimited leave policy

---

docs/tooling/calamari.md

Change-type: minor
Signed-off-by: Alexandros Sakellariou<Alexandros.Sakellariou@balena.io>

Fix fourth step link

---

docs/tooling/calamari.md

Linked-4th-path

---

docs/team/keeping-your-personal-information-up-to-date.md

Added use case examples for personal data and some minor changes
Change-type:  minor
Signed-off-by: Alexandros Sakellariou <Alexandros.Sakellariou@balena.io>
branch-name-examples of personal data use

Update keeping your personal information up to date

---

docs/culture/summit.md

Added some text and the link to the recordings
Signed-off-by: Alexandros Sakellariou <Alexandros.Sakellariou@balena.io>
branch-name-summit2022
Change-type: (e.g. [major, minor, or patch](https://github.com/balena-io/docs/blob/master/CONTRIBUTING.md#creating-commits-in-line-with-semantic-versioning))
Signed-off-by: Your Name <Youremail@balena.io>
branch-name-example

Added-summit-2022
